name: 'PR Title Check'

# This workflow validates PR titles based on conventional commit format.
# Example valid titles:
# - feat(improvement)!: [#123] - My PR title
# - feat!: [#123] - My PR title
# - feat: [#123] - My PR title

on:
  pull_request:
    types:
      - opened
      - synchronize
      - edited
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Updated to v2 for stability and performance improvements
      
      - name: Validate PR Title
        uses: Slashgear/action-check-pr-title@v4.3.0
        with:
          regexp: '^(?:release|feat|fix|build|chore|ci|docs|style|refactor|perf|test|revert)(?:\(\w+\))?!?:\s\[#\d+\]\s-\s.+'
          helpMessage: "Example: 'feat: [#123] - Update Navbar and Login in the header section'"

